### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by cr-intezra** [m-Xone/gtop#1]
This is a really nice display for GPU usage.

Is it possible to build in a flag for the fill character or go back to the old one?
    fill_char: str = "█",
    # fill_char: str = "|",
   
The new fill character - as shown on the first line - is really obtrusive and hurts the eyes. '|' was really clean and simple.

Thanks,

The Tinman

**Comment by m-Xone** [comment]
Thanks for the feedback, @cr-intezra.  Working a feature branch for this now.
